### ISSUE TITLE
Why isn't fann_copy implemented?

### ISSUE THREAD

**Issue by Zoldszemesostoros** [afck/fann-rs#2]
With a few lines of code I managed to get it to work. I might have overlooked something, because I'm not experienced with unsafe rust.
My modifications are:
```rust
pub fn copy(&self) -> FannResult<Fann> {
    unsafe { Fann::from_raw(fann_copy(self.raw)) }
}
```
in the implementation of the Fann struct, and
```rust
pub fn fann_copy(orig: *const fann) -> *mut fann;
```
in fann-sys.

**Comment by afck** [comment]
Hi! I haven't worked on this in six years, so I don't remember. You're probably right. Feel free to make a PR, then I'll merge it! (Or fork the repository if you'd like to maintain it; I'd be happy to link to your fork from the README.)
